# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: terminus/proto/core.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='terminus/proto/core.proto',
  package='terminus.core',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19terminus/proto/core.proto\x12\rterminus.core\"%\n\x07GeoPath\x12\x0c\n\x04lats\x18\x01 \x03(\x01\x12\x0c\n\x04lons\x18\x02 \x03(\x01*\x1e\n\x08Typology\x12\x08\n\x04MOTO\x10\x00\x12\x08\n\x04\x42IKE\x10\x01\x62\x06proto3'
)

_TYPOLOGY = _descriptor.EnumDescriptor(
  name='Typology',
  full_name='terminus.core.Typology',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MOTO', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BIKE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=83,
  serialized_end=113,
)
_sym_db.RegisterEnumDescriptor(_TYPOLOGY)

Typology = enum_type_wrapper.EnumTypeWrapper(_TYPOLOGY)
MOTO = 0
BIKE = 1



_GEOPATH = _descriptor.Descriptor(
  name='GeoPath',
  full_name='terminus.core.GeoPath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lats', full_name='terminus.core.GeoPath.lats', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lons', full_name='terminus.core.GeoPath.lons', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['GeoPath'] = _GEOPATH
DESCRIPTOR.enum_types_by_name['Typology'] = _TYPOLOGY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeoPath = _reflection.GeneratedProtocolMessageType('GeoPath', (_message.Message,), {
  'DESCRIPTOR' : _GEOPATH,
  '__module__' : 'terminus.proto.core_pb2'
  # @@protoc_insertion_point(class_scope:terminus.core.GeoPath)
  })
_sym_db.RegisterMessage(GeoPath)


# @@protoc_insertion_point(module_scope)
