# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: terminus/proto/device_data.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from terminus.proto import core_pb2 as terminus_dot_proto_dot_core__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='terminus/proto/device_data.proto',
  package='terminus.device_data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n terminus/proto/device_data.proto\x12\x14terminus.device_data\x1a\x19terminus/proto/core.proto\"\xe4\x01\n\nDeviceData\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x0b\n\x03jwt\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x0c\x12\x13\n\x0b\x61\x63tivity_id\x18\x04 \x01(\x0c\x12\x11\n\tdevice_id\x18\x05 \x01(\t\x12\x14\n\x0crecording_id\x18\x06 \x01(\x0c\x12)\n\x08typology\x18\x07 \x01(\x0e\x32\x17.terminus.core.Typology\x12>\n\x0e\x63ontent_format\x18\x08 \x01(\x0e\x32&.terminus.device_data.DeviceDataFormat*D\n\x10\x44\x65viceDataFormat\x12\x0b\n\x07LIVEX_1\x10\x00\x12\t\n\x05\x41PP_1\x10\x01\x12\t\n\x05\x41PP_2\x10\x02\x12\r\n\tKTM_CSV_1\x10\x03\x62\x06proto3'
  ,
  dependencies=[terminus_dot_proto_dot_core__pb2.DESCRIPTOR,])

_DEVICEDATAFORMAT = _descriptor.EnumDescriptor(
  name='DeviceDataFormat',
  full_name='terminus.device_data.DeviceDataFormat',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LIVEX_1', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='APP_1', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='APP_2', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='KTM_CSV_1', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=316,
  serialized_end=384,
)
_sym_db.RegisterEnumDescriptor(_DEVICEDATAFORMAT)

DeviceDataFormat = enum_type_wrapper.EnumTypeWrapper(_DEVICEDATAFORMAT)
LIVEX_1 = 0
APP_1 = 1
APP_2 = 2
KTM_CSV_1 = 3



_DEVICEDATA = _descriptor.Descriptor(
  name='DeviceData',
  full_name='terminus.device_data.DeviceData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='terminus.device_data.DeviceData.content', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='jwt', full_name='terminus.device_data.DeviceData.jwt', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='terminus.device_data.DeviceData.user_id', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='activity_id', full_name='terminus.device_data.DeviceData.activity_id', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='terminus.device_data.DeviceData.device_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recording_id', full_name='terminus.device_data.DeviceData.recording_id', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='typology', full_name='terminus.device_data.DeviceData.typology', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content_format', full_name='terminus.device_data.DeviceData.content_format', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=314,
)

_DEVICEDATA.fields_by_name['typology'].enum_type = terminus_dot_proto_dot_core__pb2._TYPOLOGY
_DEVICEDATA.fields_by_name['content_format'].enum_type = _DEVICEDATAFORMAT
DESCRIPTOR.message_types_by_name['DeviceData'] = _DEVICEDATA
DESCRIPTOR.enum_types_by_name['DeviceDataFormat'] = _DEVICEDATAFORMAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeviceData = _reflection.GeneratedProtocolMessageType('DeviceData', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEDATA,
  '__module__' : 'terminus.proto.device_data_pb2'
  # @@protoc_insertion_point(class_scope:terminus.device_data.DeviceData)
  })
_sym_db.RegisterMessage(DeviceData)


# @@protoc_insertion_point(module_scope)
