# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: terminus/proto/recording.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from terminus.proto import core_pb2 as terminus_dot_proto_dot_core__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='terminus/proto/recording.proto',
  package='terminus.recording',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1eterminus/proto/recording.proto\x12\x12terminus.recording\x1a\x19terminus/proto/core.proto\"\xee\x02\n\tRecording\x12\x0b\n\x03jwt\x18\x01 \x01(\t\x12)\n\x08typology\x18\x02 \x01(\x0e\x32\x17.terminus.core.Typology\x12\n\n\x02id\x18\x03 \x01(\x0c\x12\x0f\n\x07user_id\x18\x04 \x01(\x0c\x12\x13\n\x0b\x61\x63tivity_id\x18\x05 \x01(\x0c\x12\x11\n\tdevice_id\x18\x06 \x01(\x0c\x12\x0f\n\x07started\x18\x07 \x01(\x03\x12\r\n\x05\x65nded\x18\x08 \x01(\x03\x12\x33\n\x06points\x18\t \x03(\x0b\x32#.terminus.recording.Recording.Point\x1a\x8e\x01\n\x05Point\x12\x13\n\x0bsequence_id\x18\x01 \x01(\x04\x12\x0c\n\x04time\x18\x02 \x01(\x01\x12\r\n\x05speed\x18\x03 \x01(\x02\x12\x14\n\x0cposition_lat\x18\x04 \x01(\x02\x12\x14\n\x0cposition_lon\x18\x05 \x01(\x02\x12\x0b\n\x03\x65le\x18\x06 \x01(\x02\x12\x0c\n\x04pdop\x18\x07 \x01(\x02\x12\x0c\n\x04hdop\x18\x08 \x01(\x02\x62\x06proto3'
  ,
  dependencies=[terminus_dot_proto_dot_core__pb2.DESCRIPTOR,])




_RECORDING_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='terminus.recording.Recording.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence_id', full_name='terminus.recording.Recording.Point.sequence_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='terminus.recording.Recording.Point.time', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed', full_name='terminus.recording.Recording.Point.speed', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position_lat', full_name='terminus.recording.Recording.Point.position_lat', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position_lon', full_name='terminus.recording.Recording.Point.position_lon', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ele', full_name='terminus.recording.Recording.Point.ele', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pdop', full_name='terminus.recording.Recording.Point.pdop', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hdop', full_name='terminus.recording.Recording.Point.hdop', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=448,
)

_RECORDING = _descriptor.Descriptor(
  name='Recording',
  full_name='terminus.recording.Recording',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='jwt', full_name='terminus.recording.Recording.jwt', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='typology', full_name='terminus.recording.Recording.typology', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='terminus.recording.Recording.id', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='terminus.recording.Recording.user_id', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='activity_id', full_name='terminus.recording.Recording.activity_id', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='terminus.recording.Recording.device_id', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='started', full_name='terminus.recording.Recording.started', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ended', full_name='terminus.recording.Recording.ended', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='points', full_name='terminus.recording.Recording.points', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_RECORDING_POINT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=448,
)

_RECORDING_POINT.containing_type = _RECORDING
_RECORDING.fields_by_name['typology'].enum_type = terminus_dot_proto_dot_core__pb2._TYPOLOGY
_RECORDING.fields_by_name['points'].message_type = _RECORDING_POINT
DESCRIPTOR.message_types_by_name['Recording'] = _RECORDING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Recording = _reflection.GeneratedProtocolMessageType('Recording', (_message.Message,), {

  'Point' : _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
    'DESCRIPTOR' : _RECORDING_POINT,
    '__module__' : 'terminus.proto.recording_pb2'
    # @@protoc_insertion_point(class_scope:terminus.recording.Recording.Point)
    })
  ,
  'DESCRIPTOR' : _RECORDING,
  '__module__' : 'terminus.proto.recording_pb2'
  # @@protoc_insertion_point(class_scope:terminus.recording.Recording)
  })
_sym_db.RegisterMessage(Recording)
_sym_db.RegisterMessage(Recording.Point)


# @@protoc_insertion_point(module_scope)
